site_name: Jacob Fintech Book
site_description: "Jacob's Fintech 基础教程"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2021-9999 Jacob Xi"

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"
  - '区块链技术': 
    - '1 区块链的革命性及技术概要': '1blockchain/1theory.md'
    - '2 区块链技术细节（哈希算法/加密和挖矿)' : '1blockchain/2techs_intro.md'
    - '3 区块链技术去中心化的共识机制': '1blockchain/3decentralised.md'
    - '4 区块链技术智能合约' : '1blockchain/4contract.md'
    - '5 区块链技术传统金融和虚拟货币': '1blockchain/5fintech.md'
  - 'Autosys CA':
    - '1 Autosys Introduction': 'autosys/1Autosys_tot1.md'
    - '2 Autosys JIL': 'autosys/2Autosys_jil.md' 
    - '3 Autosys Components, Configuration & Validation': 'autosys/3Autosys_comp.md' 
    - '4 Austosys command': 'autosys/4Autosys_cmd.md' 
    - '5 Manage Job in the Database': 'autosys/5Autosys_job_cmd.md' 
    - '6 Autotsys virtual resource management': 'autosys/6autosys_vir_resouce.md'  
    - '7 Shell Script to check Autosys agent installed': 'autosys/7autosys_shell.md'
  - 'Agile fundamental':
    - '1 Agile Intro': 'agile/1agile_intro.md'
    - '2 Agile Block Learn': 'agile/2agile_block.md'
    - '3 Agile Action': 'agile/3agile_action.md'

repo_url: https://github.com/Chao-Xi/jxfintechbook.git
repo_name: "jxfintechbook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  palette:
    primary: 'teal'
    accent: 'teal'
  i18n:
    prev: 'Previous'
    next: 'Next'